### ISSUE TITLE
Change method names to standardized names

### ISSUE THREAD

**Issue by tobiaslins** [mpay24/mpay24-php#42]
In order to understand the mpay24 sdk, it is neccessary to adapt all public methods to standardized names.
Here a list for the mapping:

| SOAP Call        | Method Name           | 
| ------------- |:-------------:|
| selectPayment | paymentPage |
| acceptPayment | payment |
| manualCredit | refund |
| manualReverse | cancel |
| manualClear | capture |
| createPaymentToken | token |
| acceptWithdraw | payout |
| transactionStatus | paymentStatus |
| transactionHistory | paymentHistory |
| createProfile | createCustomer |
| listProfiles | listCustomers |
| deleteProfile | deleteCustomer |
| listNotCleared | listAuthorizations |
| listPaymentMethods | paymentMethods |

**Comment by stefanpolzer** [comment]
@tobiaslins basically a very good Idea. But to be clear this MUST be link  or added to the Page https://docs.mpay24.com/docs/soap-interface otherwise none understand it, it took me days with the current documentation.

**Comment by tobiaslins** [comment]
@stefanpolzer 
We add this mapping as soon as the new sdk version is going to be released!

**Comment by stefanpolzer** [comment]
@tobiaslins not all of them are implement right now right!
I tested the most of them with the last Version in psr4branch  successful:

- paymentPage()
- token();
- payment() with TOKEN and PROFILE
- refund()
- paymentStatus() // with a mPAYTID
- paymentStatusByTid()  // with
- paymentMethods()

On two methods I got an Response with Status ERROR from the Server:
But maybe this is because I did it wrong:

- capture()
- cancel()

The following ar not implemented yet:

- createCustomer()
- listCustomers()
- deleteCustomer()
- listAuthorizations()
- payout()
- paymentHistory()

**Comment by stefanpolzer** [comment]
paymentHistory()  done see https://github.com/mpay24/mpay24-php/pull/45/commits/f11b1eb7effcadd52a4e95011eabdd571443d316

**Comment by stefanpolzer** [comment]
SOAP ManualCallback is missing in this List
